### PR TITLE
empty session view fix

### LINKED ISSUE #441: Change to use vertical chain style and change scrollable in my plan's empty view
## Kind (Required)

- Improvement

 ## Overview (Required)

- This empty view should locate center position with a little top margin.
- We can't view screen because of non-scrollable😭

 ## Screenshot
device-2020-01-18-180302

## Links
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=11%3A432

### PR DESCRIPTION
**Pull request by shinya-takano**
adjust margin to centering layout

## Issue
- close #441 

## Overview (Required)
- margin centering to constraint layout centering
- warning fix contentDescription is null

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
LGTM 🔖

**Comment by takahirom** [comment]
Please fix conflict 🙏

**Comment by shinya-takano** [comment]
what's happen?

https://github.com/DroidKaigi/conference-app-2020/commit/f754ecae2382a444356645ac74ef7e7145af34fb

fragment_bottom_sheet_favorite_session was deleted...

Should this pull request be closed?

**Comment by takahirom** [comment]
The date and your favorite fragments have been merged into one.👍

**Comment by shinya-takano** [comment]
I understand.
check merged screen. I think this issue resolved.

merged

**Comment by shinya-takano** [comment]
Who should close this pull request?

**Comment by shinya-takano** [comment]
none merge file. close this pullrequest and issue

**Pull request closed without merging**
