### PR TITLE
Fix ktlint error

### PR DESCRIPTION
**Pull request by hkusu**
## Issue
- N/A

## Overview (Required)
- Fix ktlint error
- This makes the "On release branch" workflow green
  - https://github.com/DroidKaigi/conference-app-2020/actions?query=workflow%3A%22On+release+branch%22

## Links
- N/A

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👍

**Comment by hkusu** [comment]
Error.. 🤔

**Comment by takahirom** [comment]
> Cannot allocate memory 

I retry!

**Comment by mhidaka** [comment]
@hkusu Thanks! I merged!

**Pull request merged**
