### PR TITLE
[WIP] Remove SearchView start margin

### LINKED ISSUE #101: Remove SearchView start margin
## Kind (Required)

- Improvement

 ## Overview (Required)

- Remove `SearchView` start margin.
- Fix hint start position.

 ## Links	

-

### PR DESCRIPTION
**Pull request by Luecy1**
## Issue
- close #101

## Overview (Required)
- SearchView is reimplemented in layout.xml instead of menu.xml 

## Screenshot
Before | After
:--: | :--:
 | 

## Todo
- (bug?) keybord not appeared at first one.
- reimplement SearchView function(in onCreateOptionsMenu Method)
- Conflict resolution :weary:

### CODE REVIEW

**Comment by takahirom** [comment]
@Luecy1 If you have any questions please tell me. 🙏

**Comment by Luecy1** [comment]
@takahirom 
I have a question in here ↓
 https://github.com/DroidKaigi/conference-app-2020/issues/101#issuecomment-576210780

**Comment by takahirom** [comment]
This is just an idea, but is it difficult to access from requireActivity.supportActionBar?

**Comment by Luecy1** [comment]
Its safe that calling from Fragment to Activity.

**Comment by Luecy1** [comment]
Umm, I can not find SearchView.
I want give up.

It's difficult for me. 😢
I'm sorry.🙇‍♂️

**Pull request closed without merging**
