### PR TITLE
[iOS] Enable file_header rule to ban header comments

### PR DESCRIPTION
**Pull request by woxtu**
## Issue
- None

## Overview (Required)
- Same the title

## Links
- https://github.com/DroidKaigi/conference-app-2020/pull/447#discussion_r368300240
- https://realm.github.io/SwiftLint/file_header.html

### CODE REVIEW

**Comment by ry-itto** [comment]
Thanks! This is nice 😄 

But I find SwiftLint doesn't work for untracked files. Please fix with this?
I think we should fix `scripts/lint.sh`. 🙏

**Comment by woxtu** [comment]
True. Let me think about it.

**Comment by ry-itto** [comment]
🙏

**Comment by ry-itto** [comment]
@woxtu 
```shell
git status --porcelain | awk -F'"' '{print $2}'i | grep -e '\(.*\).swift$'
```
This script is useful to fulfill above. 😄

**Comment by woxtu** [comment]
@ry-itto This is it! I didn't know `--porcelain`.

This is my answer:

```sh
git status --porcelain | grep -e '^[ ?][^D] ".*\.swift"$' | awk -F'"' '{print $2}'
```

**Comment by ry-itto** [comment]
Oh, thanks to fix both of `lint.sh` and `format.sh` 😄 

LGTM 👍

**Pull request merged**
