### PR TITLE
[discussion]Add fade animation when drag bottomsheet

### LINKED ISSUE #484: Fading animation is delayed when bottom sheet expanded.
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is a difference in the way of delay depending on how to operate.
- When you tapped the `expand_less` icon to expand bottom sheet, recyclerView appears dimmed and it appears correct after a few seconds.
- When you swiped the bottom sheet header to expand bottom sheet, recyclerView doesn't appear and it appears after a few seconds.

 ## Gif
output

### PR DESCRIPTION
**Pull request by koji-1009**
## Issue
- close #484 
※This pr is for discussion #484

## Overview (Required)
- Add fade animation when dragging bottom sheet.

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by koji-1009** [comment]
@umechanhika 
Hi, could you check DeployGate?
Hopefully it's close to what you suggested one.

**Comment by umechanhika** [comment]
@koji-1009 
Thank you for modifications.
It looks good to me!

**Comment by koji-1009** [comment]
@takahirom 
Hi, #762 is great approach!
So if you merged #762, please close this pr.

I think this conference app will be more interesting if it is more experimental 😆

**Comment by takahirom** [comment]
Thanks!

**Pull request closed without merging**
