### PR TITLE
move unit test to test folder

### LINKED ISSUE #614: a few files in jvmTest are not recognize dependency libraries.
**Overview (Required)**
- can't recognize klock and junit in file of  jvmTest folder.

**Steps To Reproduce**
No
**Expected behavior**
No

**Screenshots**
If applicable

**Env:**
latest master branch

**Additional context**
No

### PR DESCRIPTION
**Pull request by a25max**
## Issue
- close #614 

## Overview (Required)
- I want to fix for cant recognize library in class of jvmTest folder. Unit test class move to test/java folder.

## Links
No

## Screenshot
No

### CODE REVIEW

**Comment by takahirom** [comment]
Does that tests failed? 👀

**Comment by a25max** [comment]
Yes, I can't understand this test so I may resolve this test more time.

**Comment by a25max** [comment]
I think I should mod Filters class.

**Comment by a25max** [comment]
Sorry, give up 😭

**Comment by roana0229** [comment]
No worries. 😄 
Thank you for your challenge 👍 
Could you please close this PR ?

**Comment by a25max** [comment]
OK, I see. Thank you 🙏

**Pull request closed without merging**
