### PR TITLE
Fix to show FilterChip showing all correctly

### PR DESCRIPTION
**Pull request by wakwak3125**
## Issue
- No

## Overview (Required)
- The last FilterChip does not show correctly.
- I Added more paddingBottom

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Ideally, I want to set it dynamically.  How about setting here?
https://github.com/DroidKaigi/conference-app-2020/blob/b232e8ca2abbcb51a79b4f88ebb152defcedab63/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt#L116

**Comment by wakwak3125** [comment]
Sorry, I didn't realize that peek height set dynamically 🙏 
OK! I'll change my codes 👍

**Comment by takahirom** [comment]
@wakwak3125 If you have any questions. Please tell me 🙏

**Comment by wakwak3125** [comment]
Sorry, I didn't have a time to do this 🙏
I'll make finish this PR in a week. 

Is it ok?

**Comment by jmatsu** [comment]
Yes, sure but take it easy~

**Comment by wakwak3125** [comment]
@takahirom 
Sorry for late 🙏 
I set `initalPeekHeight` and additional `24dp` to `paddingBottom`.
I watched the [Figma](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=11%3A625), and this `paddingBottom` should have `40dp`.

image

**Pull request merged**
