### PR TITLE
Add SessionListTest

### LINKED ISSUE #594: Add unit tests for SessionList
## Kind (Required)

- Improvement

 ## Overview (Required)

- That class contains many logics!

 ## Links	

-

### PR DESCRIPTION
**Pull request by shiraji**
## Issue
- close #594 

## Overview (Required)
- Add test cases for SessionList
- Since I didn't know much of SessionList, I created test cases based on actual code. Please point out if there are test cases that are unnecessary.

## Links
N/A

## Screenshot
N/A

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you as always!  
This time it's okay because it doesn't run on Android, but I avoided using white space in method names because Android doesn't support spaces.  
What do you think?
https://discuss.kotlinlang.org/t/android-issue-with-backticked-method-names/66

**Comment by shiraji** [comment]
let me replace spaces with _ ?

**Comment by takahirom** [comment]
I also like spaces, but please replace them with underbars this time.🙏

**Comment by shiraji** [comment]
sure!

**Comment by shiraji** [comment]
Fixed them and squash commits.

**Comment by takahirom** [comment]
LGTM! Thank you for contribution!🙏

**Pull request merged**
