### PR TITLE
Fix fade out myPlan's emptyView after visible my plan list

### LINKED ISSUE #385: Fade out myPlan's emptyView after visible my plan list
## Kind (Required)

- Improvement

 ## Overview (Required)

- EmptyView see for a moment in spite of having favorite sessions when specific cases.
    - 1. When opening app and slide to myPlan tab firstly.
    - 2. When moving to session detain and come back to myPlan screen.
- Should set to gone visibility in default value?🐶

 ## Screenshot

### PR DESCRIPTION
**Pull request by b4tchkn**
## Issue
- close #385 

## Overview (Required)
- Set visibility to eliminate the visibility of empty_session

## Screenshot
Before | After
| :--: | :--: |
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry, can you check master branch? 🙇

**Comment by b4tchkn** [comment]
I checked master branch and resolved conflicts. Is this correct?

**Comment by takahirom** [comment]
Maybe the same fix is written in other ways.
Unfortunately, it seems to have been fixed by another PR.

```
            app:isInvisible="@{isCollapsed || !isEmptySessions}"
            android:visibility="@{isEmptySessions ? View.VISIBLE : View.GONE}"
```

**Comment by takahirom** [comment]
Sorry, let me close.
We look forward to your next contribution 🙏

**Pull request closed without merging**
