### PR TITLE
Fix options menu not shown when rotate

### LINKED ISSUE #388: Content area must be scrollable and viewable in preparation for screen rotation
## Kind (Required)

- Improvement

 ## Overview (Required)

- Sometimes, we can't view screens because of non-scrollable and non-margin.
- Please try look into various screen layout for refactoring!

 ## Screenshot	
For example, just like this.

device-2020-01-18-180302

### PR DESCRIPTION
**Pull request by 5hyn3**
## Issue
- close #388

## Overview (Required)
- Fix bug that options menu not shown when the screen is rotated.
  - Investigate by the layout inspector, OptionsMenu was drawn. But, it's position was wrong.Call `invalidateOptionsMenu()` when `doOnApplyWindowInsets` then it was resolve.

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
I googled. Is this related?
https://github.com/takahirom/conference-app-2020/blob/master/android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt#L169
https://stackoverflow.com/a/29541621/4339442

**Comment by 5hyn3** [comment]
> Thanks!
> Since I do not know the cause, I'm afraid that I have to put this code everywhere. 👀
> I googled. Is this related?
> https://github.com/takahirom/conference-app-2020/blob/master/android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt#L169
> https://stackoverflow.com/a/29541621/4339442

Thanks for providing helpful link!

In conclusion, commenting out `setTitle (...)` did not solve the problem.
The problem seems to have occurred because did not consider that navigationBar was hidden.
Checking the coordinates of OptionMenus, it seems to exist at the position of NavigationBar.

So this problem can also be solved by commenting out the following: (But the UI collapses.)

https://github.com/takahirom/conference-app-2020/blob/master/android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/SystemUiManager.kt#L62

Of course, I didn't want to take any measures to break the UI, so I decided to call `invalidateOptionsMenu ()`.

**Comment by takahirom** [comment]
I have a question 🙋 
There are several other View events, but why do you do this at the time of doOnApplyWindowInsets? 👀

**Comment by 5hyn3** [comment]
From the above information, I speculated that this problem was caused by the behavior of ApplyWindowInsets due to a change in systemUiVisibility.
So call invalidApplyMenus () in doOnApplyWindowInsets.
But I'm not very familiar with the behavior around WindowInsets.
While studying, I survey for better timing. 🙇

**Comment by takahirom** [comment]
Thanks! Can you add a comment like this?

```
// Invalidate because option menu cannot be displayed after screen rotation
```

**Comment by 5hyn3** [comment]
OK! I add it ASAP!

**Comment by 5hyn3** [comment]
Comment added!

**Comment by takahirom** [comment]
LGTM 👍 Thank you for investigating!!

**Pull request merged**
