### PR TITLE
fix update gradle plugin rc2 to rc3

### LINKED ISSUE #801: Update Android Gradle Plugin 3.6 RC3
## Kind (Required)

- Improvement

 ## Overview (Required)

- Android Studio 3.6 RC3 was released on February 10

 ## Links	

- <https://androidstudio.googleblog.com/2020/02/android-studio-36-release-candidate-3.html>

### PR DESCRIPTION
**Pull request by yoshida0261**
## Issue
- close #801 

## Overview (Required)
- update gradle plugin version

### CODE REVIEW

**Comment by takahirom** [comment]
LGTM! 👍 
By the way, If you want to add contributors. You can add an email to commit. 😄 
git config --global user.email your@email.com
https://github.com/DroidKaigi/conference-app-2020/graphs/contributors

**Comment by takahirom** [comment]
If you want to amend the commit. I will wait.
Do you want to merge? 👀

**Comment by yoshida0261** [comment]
I'll fix it, so please wait a moment.

**Comment by yoshida0261** [comment]
Email has been modified.

**Comment by takahirom** [comment]
Thanks!

**Pull request merged**
