### PR TITLE
Toggle expand icon of BottomSheet sub header label on MYPLAN tab

### LINKED ISSUE #310: When BottomSheet is collapsed, sub header label should change on `MYPLAN`
## Kind (Required)

- Improvement

 ## Overview (Required)

- My plan did not change expand icon.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/issues/112
- https://github.com/DroidKaigi/conference-app-2020/pull/263

### PR DESCRIPTION
**Pull request by sekiya9311**
## Issue
- close #310 

## Overview (Required)
- subscribe `uiModel.expandFilterState` and toggle Button / ImageView
- subscribe `uiModel.expandFilterState` and hide session list when collapsed
- I Implemented based on #263 

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by roana0229** [comment]
👀

**Comment by roana0229** [comment]
@sekiya9311 
Thanks for your contribution ! It's good 👍 
And, could you please hide list when session is collapsed ?

**Comment by sekiya9311** [comment]
got it !

**Comment by roana0229** [comment]
Thank you very much. LGTM 👍

**Pull request merged**
