### PR TITLE
Fix bottom sheet click area

### LINKED ISSUE #393: Dynamically expand the tappable area when collapsed session filter
## Kind (Required)
- Improvement

 ## Overview (Required)

- Move the line down as you scroll to expand the tappable area.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/pull/367#issuecomment-575868989
- [About MotionLayout](https://developer.android.com/reference/android/support/constraint/motion/MotionLayout)

### PR DESCRIPTION
**Pull request by kazaman97**
## Issue
- close #393

## Overview (Required)
- Add clickable and fixed tap area of bottom sheet.

## Links
-

## Screenshot
No screenshot

### CODE REVIEW

**Comment by kazaman97** [comment]
This is not the proposed method, but how about it?

**Comment by takahirom** [comment]
Sorry, I don't understand. Why make it clickable??

**Comment by kazaman97** [comment]
@takahirom 
https://github.com/DroidKaigi/conference-app-2020/issues/393#issuecomment-576258954
I was told that there is a blank space at the bottom with no response, 
so I fixed by adding clickable.
Did the request differ??

Title was misspelled and fixed🙇🏻‍♂️

**Comment by takahirom** [comment]
すみません、日本語で書きます 🙇 
もともとジェスチャーナビゲーションで、フィルターが見える状態から、フィルターを隠してセッションを表示するときに、指を下から上にスワイプするとジェスチャーナビゲーションのせいでアプリ切替画面に行ってしまうという問題がありました。
それに対して、ジェスチャーナビゲーションのときは下に空白の領域を足しました。
ただ、これだと、ただ上に上げただけなので、謎の白い領域が目立ちます。
そのため、この黒い線を、フィルターが見えるのに応じて、下に下げることができればいい感じに解決するのではないかと考えました。
つまりやりたいのは"フィルターが見えたときに線を下に下げたい"ということです。 🙇 
image

**Comment by kazaman97** [comment]
Thank you for explaining in Japanese.
And I'm sorry I couldn't understand the contents🙇🏻‍♂️
So you recommended MotionLayout.
Now that I understand the content, I will try again🙇🏻‍♂️

**Comment by takahirom** [comment]
@kazaman97 If you have any questions, Please tell me 🙏

**Comment by takahirom** [comment]
@kazaman97 How about that? I think this implementation is difficult. 😄

**Comment by takahirom** [comment]
Thanks! Also I am trying this! (Because there was no reaction.  .)
https://github.com/DroidKaigi/conference-app-2020/pull/762

**Comment by kazaman97** [comment]
@takahirom 
I can't reply or commit, I'm very sorry.
My implementation is performed so that the motion layout can be moved based on the amount of change in the bottom sheet.
However, because of my low technical ability, perfect implementation was not possible.

**Comment by kazaman97** [comment]
Also, as a problem now,
- How do you manage tab-by-tab values?
- How to pass BottomSheet value?
I do not it understand.

**Comment by takahirom** [comment]
I will try that! You can check #762 🙏

**Comment by kazaman97** [comment]
I am sorry for my lack of ability. 🙇🏻‍♂️
I understand. I will also check. #762

**Pull request closed without merging**
