### PR TITLE
Fix place holder color should be colorPrimary on Android 5.0

### LINKED ISSUE #132: Place holder color should be colorPrimary on Android 5.0
## Kind (Required)

- Improvement

 ## Overview (Required)

- Place holder color is should be colorPrimary on Android 5.0

image

 ## Links	

-

### PR DESCRIPTION
**Pull request by nukka123**
## Issue
- close #132 

## Overview (Required)
- Use `AppCompatResources.getColorStateList()` instead of `ContextCompat.getColor()`.
- I also fix similar issue code (`search_button`, `search_close_button`).

## Links
-

## Screenshot
Before | After | After (Dark)
:--: | :--: | :--:
 |  |

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks! When getting from layout XML, is this issue not occurred? 🙋

**Comment by nukka123** [comment]
@takahirom 

I think yes.
Probably it has supported since appcompat rev.24.

ColorStateList doc said
> [ColorStateList > Item attributes](https://developer.android.com/reference/android/content/res/ColorStateList#item-attributes)
> -- in API 23 and above -- a theme attribute that resolves to a color.

support library release notes said
> [Revision 24.0.0](https://developer.android.com/topic/libraries/support-library/rev-archive#rev24-0-0)
> Changes for v7 appcompat library:
> Added support for referencing themed ColorStateList objects from XML

It seems that appcompat views use a `AppCompatResources.getColorStateList()` via [TintTypedArray](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/main/java/androidx/appcompat/widget/TintTypedArray.java;l=178;drc=5e1cddb861d7c49fda89354edbcf1637b43af064) etc.

And also, for example, the following `TextView` has not occurred this issues.

```
item_speaker.xml

        <TextView
            android:id="@+id/name"
            ...
            android:textColor="@color/speaker_name"
            ...
            />
```

**Comment by takahirom** [comment]
LGTM!🙏🙏

**Comment by nukka123** [comment]
競合解決したらBotさんからの指摘が大変なことに。。
@takahirom どうしましょう？ 私の方で修正した方が良いですか？

**Comment by jmatsu** [comment]
すみません、盛大に無視してください・・・ 🙇

**Comment by nukka123** [comment]
@jmatsu 了解です 🤘

**Pull request merged**
