### PR TITLE
Add Adaptive Icon

### LINKED ISSUE #191: Adaptive Icon
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is a design in Figma !!
https://github.com/DroidKaigi/conference-app-2020#design

### PR DESCRIPTION
**Pull request by fornewid**
## Issue
- close #191 

## Overview (Required)
- Add Adaptive Icon 

## Link
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=43%3A4

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thanks 👍 
You can use the foreground and background image.
https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=43%3A4
Please use Android Icon BG for background 🙏

**Comment by fornewid** [comment]
🙆‍♂ 🙆‍♂ 🙆‍♂

**Comment by fornewid** [comment]
I changed adaptive icon using official resources.
But... icon symbols are small slightly.
Is it normal? 🤔

**Comment by takahirom** [comment]
Thank you for feedback. The design is updated. Can you update icons? 🙏

**Comment by fornewid** [comment]
:see_no_evil: It's a little dizzy.

**Pull request merged**
