### PR TITLE
replace keystore sha256 with rsa alg

### PR DESCRIPTION
**Pull request by sdsd08013**
## Issue
- https://github.com/DroidKaigi/conference-app-2020/issues/382

## Overview (Required)
- build apks by bundletool is failed because of invalid key size of keystore alg

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
@sdsd08013 Why you close this PR..? 😭

**Comment by sdsd08013** [comment]
@takahirom 
sorry!
I'm not exactly sure debug.keystore(SHA256withDSA) throw this exception, So I need time to investigate this exception.
Now I'm debugging bundletool and keystore on local machine.

If you are in a hurry, I reopen pull request.(Regardless wether I do or not, I reopen pull request within a few days)

**Comment by takahirom** [comment]
Thanks!

**Comment by sdsd08013** [comment]
@takahirom 
I reopen PR, please check it 🙏 
https://github.com/DroidKaigi/conference-app-2020/pull/536

**Pull request closed without merging**
