### PR TITLE
Change specific chip's color in session detail screen

### LINKED ISSUE #436: Change specific chip's color in session detail screen
## Kind (Required)

- Improvement

 ## Overview (Required)

- To check session's better important information, some chips should be changed color from the other chips color.
    -Please change color about `language` and `for beginner` chips.

 ## Image	
スクリーンショット 2020-01-19 19 32 33

### PR DESCRIPTION
**Pull request by ttanaka330**
## Issue
- close #436

## Overview (Required)
- Set `category` and `language` chip color  
- `for beginners` chip is not displayed, so no color is set.  https://github.com/DroidKaigi/conference-app-2020/issues/436#issuecomment-575999955

## Links
-

## Screenshot
Before | After
:--: | :--:
 | 
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Is it ok when dark theme?? 🌚

**Comment by takahirom** [comment]
We can create XML like this 👀 
https://github.com/DroidKaigi/conference-app-2020/blob/master/feature/session/src/main/res/color-night/search_icon.xml

**Comment by ttanaka330** [comment]
Thanks for the hint!

I forget the dark theme.
Is there a color specification for the dark theme?
Does `category` match colorOnSurface?

**Comment by takahirom** [comment]
No specifications. You can choose for your senses. 😄

**Comment by ttanaka330** [comment]
For dark theme colors, set colors that have changed saturation from light theme.
The colors of the light theme have also changed to match Figma.

**Comment by takahirom** [comment]
Looks Great!! Thanks!

**Comment by ttanaka330** [comment]
Thanks for the review.
By the way, branches don't merge, what do I do?

**Comment by takahirom** [comment]
Thanks I just forgot it 🙇🙇

**Pull request merged**
