### PR TITLE
Try to create universal apk

### LINKED ISSUE #217: Fix crash when opening contributor and settings
## Kind (Required)

- Other

 ## Overview (Required)

-  Probably we should upload aab instead of apk to deploy gate 🚀 

 ## Links	

-

### PR DESCRIPTION
**Pull request by takahirom**
## Issue
- close #217

## Overview (Required)
- Create universal apk for fixing issue
- 🙏 

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by ypresto** [comment]
💭 IMO 62MB is too big to be directly placed to Git 🙈

**Comment by takahirom** [comment]
The jar is built by hand for using the new R8 version. 
Where do you know any good place to upload?

**Comment by ypresto** [comment]
I personally prefer to use `Releases` feature of GitHub to place build artifacts. 😃

(It's hard to say, but, you can `git rm` but you can't actually remove 62MB file object from the history without force-push. 🙈)

**Comment by takahirom** [comment]
Hmm. The jar is not the DroidKaigi app artifact. 🤔 
And without this, the app will crash 😭

**Comment by ypresto** [comment]
Ahh I have just understood for what you are using it. It's https://github.com/google/bundletool/releases , and it's only used in Travis CI?

My recommendation for CI is to download build dependency at each build and cache it if necessary (same as maven deps).

**Comment by takahirom** [comment]
The Jar is built by hand. So the jar is not uploaded.
Please see this issue 🙇 
https://github.com/DroidKaigi/conference-app-2020/issues/217#issuecomment-574545550

**Pull request merged**
