### PR TITLE
Suppress const modifier lint warning on Dep.kt

### PR DESCRIPTION
**Pull request by chibatching**
## Issue
- close Nothing()

## Overview (Required)
- Suppress `const` modifier lint warning to `Dep.kt`

## Links
- none

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Because it is simple, I prefer to suppress without const, but is it better to do so? 👀

**Comment by chibatching** [comment]
Yes, it has just a bit performance advantage.
If you prefer to suppress warning, I'd revert the code and change suppress warning.

**Comment by chibatching** [comment]
Hi, I changed the way to remove warnings.
I added suppress rule `MayBeConstant` to `Dep.kt`, and organize commit by rebasing.

**Comment by takahirom** [comment]
Thanks! LGTM 🙏

**Pull request merged**
