### PR TITLE
Upgrade Gradle to 6.1

### PR DESCRIPTION
**Pull request by kubode**
## Overview (Required)
- Upgrade Gradle to the latest version

## Command

```sh
$ ./gradlew wrapper --distribution-type all --gradle-version 6.1
```

### CODE REVIEW

**Comment by takahirom** [comment]
I hope it does not affect Kotlin MPP.
Can you check this?

```
BUILD_IOS=true ./gradlew :ios-combined:linkIosX64 -PXCODE_CONFIGURATION=DEBUG
```

**Comment by takahirom** [comment]
And does Session.kt or ResponseToModelMapper.kt appear in Android Studio without an unresolved reference? 🙏

**Comment by kubode** [comment]
The following command works on my local.

Xcode Tools Version: 11.3.1

```sh
$ BUILD_IOS=true ./gradlew :ios-combined:linkIosX64 -PXCODE_CONFIGURATION=DEBUG
```

And there is no errors both of `Session.kt` and `ResponseToModelMapper.kt` after synced.

image

**Comment by takahirom** [comment]
Thanks! LGTM!

**Pull request merged**
