### PR TITLE
Gem cache not stored.

### LINKED ISSUE #255: Gem cache not stored.
**Overview (Required)**
- Gem cache failed in CI(GitHub Actions) at pull request.
- For example, https://github.com/DroidKaigi/conference-app-2020/runs/390543966 .

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

スクリーンショット_2020-01-15_16_33_25

**Env:**

**Additional context**

Probably it should be modified as follows.

`bundle install --path=vendor/bundle --jobs=4 --clean --gemfile=.ci/Gemfile`
↓
`bundle install --path=./vendor/bundle --jobs=4 --clean --gemfile=.ci/Gemfile`

### PR DESCRIPTION
**Pull request by Takafumi-Orita**
## Issue
- close #255

## Overview (Required)
Fix-Gem cache not stored

## Links
https://github.com/DroidKaigi/conference-app-2020/compare/master...Takafumi-Orita:Fix_ci?expand=1#diff-3e808f84fba6a3eccf009fc20119d00d

### CODE REVIEW

**Comment by hkusu** [comment]
👍

**Comment by hkusu** [comment]
Should change cache key.

```
- uses: actions/cache@v1
   with:
     path: ~/vendor/bundle ← this
     key: ${{ runner.os }}-bundle-${{ hashFiles('.ci/Gemfile.lock') }}
```

**Comment by jmatsu** [comment]
Thank you @hkusu 

@Takafumi-Orita 
The expected behaviour is to make a cache of `.ci/vendor/bundle` as described in [a comment](https://github.com/DroidKaigi/conference-app-2020/issues/255#issuecomment-574540721). 
Could you please resolve the issue again? Thanks.

**Comment by hkusu** [comment]
Looks good 👍

**Comment by takahirom** [comment]
For your reference, If you add an email to commit. You can leave your commit in contributors.  
https://github.com/DroidKaigi/conference-app-2020/graphs/contributors

```
git config --global user.email your_github_registered_email@example.com
```

Probably you can read this.
https://tech-1natsu.hatenablog.com/entry/2018/10/19/021855

**Comment by Takafumi-Orita** [comment]
@hkusu @jmatsu @takahirom 
Thank you for teaching me carefully.
Is this okay?

**Comment by jmatsu** [comment]
Looks good! Thank you for your contribution!

**Pull request merged**
