### PR TITLE
Expand front layer when back button pressed

### LINKED ISSUE #126: If you back gestured or pressed when front layer is inactive, activate it
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)
- when user complete filtering session by tags, some users may do back action.
    - If user viewing session screen with no back stacks, app will close.
- `inactive front layer` is `BottomSheet expanded`
- `active front layer` is `BottomSheet collapsed`

 ## Links	

- https://material.io/components/backdrop/#behavior

### PR DESCRIPTION
**Pull request by gen0083**
fix issue #126

## Issue
- close #126 

## Overview (Required)
- handle back button pressed with OnBackPressedDispatcher
- handle event only if filter appeared (front layer collapsed) because if callback always enabled we cannot back to home 😢 
- it's my first time to use OnBackPressedDispatcher so I'm glad to tell me if you know how to pass back-button pressed event to default behavior

## Links
- https://developer.android.com/guide/navigation/navigation-custom-back

## Screenshot
Before | After
:--: | :--:
before | after

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thanks👍
When app collapse 2 tabs.We can not close app.👀

**Comment by gen0083** [comment]
got it. i'll fix it 💪

**Comment by gen0083** [comment]
update, backPressedCallback enabled only if fragment is shown (meant onResume) and front layer is collapsed (meant filter is shown).

**Comment by takahirom** [comment]
It's working nicely! The code is a bit complicated, so I'm thinking about making it easy.

**Comment by gen0083** [comment]
yah, i rethink too. 😄

**Comment by takahirom** [comment]
Thanks! It seems better. But this has bug.  😭 
show filter → system task list -> droidkaigi -> back (not handled  )

**Comment by gen0083** [comment]
😇 
it seems to be needed callback enable on onResume.
I'll fix it.

**Comment by gen0083** [comment]
fixed 🙇 

by the way, how do you think about this behavior.
when drawer is opened and filter is shown, it closed filter on back button pressed.
it looks a little bit strange.
we should close drawer with back button same with this issue?

with_drawer

**Comment by takahirom** [comment]
Can you open an issue? 🙇

**Comment by gen0083** [comment]
sure 😄

**Pull request merged**
