### PR TITLE
Change BottomSheet sub header label when collapsed

### LINKED ISSUE #112: When BottomSheet is collapsed, sub header label should change.
## Kind (Required)

- Improvement

 ## Overview (Required)

- When the back layer is active, change sub header design

 ## Links	

- https://material.io/components/backdrop/

## Screenshot
Current | Design
:--: | :--:
 |

### PR DESCRIPTION
**Pull request by okuzawats**
## Issue
- close #112 

## Overview (Required)
- add expand less icon, and display it in ImageView. ImageView is in FrameLayout in order to expand tap area.
- subscribe `uiModel.expandFilterState` and toggle Button / ImageView
- `filtered_session_count` is constrained to `start_filter` , so toggled visibility of `start_filter` to INVISIBLE, not GONE
- not implemented:
  - ripple effect of icon
  - MYPLAN tab: it need to have `ExpandFilterState` to implement, i'm afraid that it lead to enlarge this PR

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by roana0229** [comment]
👀

**Comment by roana0229** [comment]
Thanks, very good 👍 
I confirmed that applicatble session count was displayed !

**Comment by roana0229** [comment]
> - not implemented:
>   - ripple effect of icon
>   - MYPLAN tab: it need to have ExpandFilterState to implement, i'm afraid that it lead to enlarge this PR

@okuzawats  Please, would you create a new issue about ripple effect ?

**Comment by okuzawats** [comment]
@roana0229 thanks. I created a new issue, please check it out #267

**Comment by roana0229** [comment]
Thank you for your quick work!

**Pull request merged**
