### PR TITLE
#170 Change to an easy-to-understand error message

### LINKED ISSUE #170: Change to an easy-to-understand error message
## Kind (Required)

- Improvement

 ## Overview (Required)

- This is the current message. Probably we should use text as "Connection attempt failed. Please try again."
image

 - You can change error messages here. https://github.com/DroidKaigi/conference-app-2020/blob/master/corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ext/AppErrors.kt#L34

 ## Links	

-

### PR DESCRIPTION
**Pull request by felix925**
## Issue
- close #170

## Overview (Required)
-Change "error_unknown" messages value in corecomponent/androidcomponent/src/main/res/values/strings.xml
"Error unknown" to "Connection attempt failed.Please try again."
## Links
-https://github.com/felix925/conference-app-2020/blob/master/corecomponent/androidcomponent/src/main/res/values/strings.xml#42

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by roana0229** [comment]
👀

**Comment by takahirom** [comment]
Thank you for your contribution 🎉 
"error_unknown" is a string used when an unknown error occurs in the app.
So, for example, I want to add a word like "An unknown error has occurred." for the user.
I just want to make the messages for error_network, error_server, and error_unknown easier for the user to understand.
(エラーメッセージが今は"不明なエラー"などになっているので、それをerror_network, error_server, error_unknownそれぞれに対して"不明なエラーが発生しました。後ほどやり直してください"のようにわかりやすいメッセージにしたいだけです 🙇 )

**Comment by felix925** [comment]
I see!
Correct and update the pull request.

**Comment by felix925** [comment]
I have a question.
Should I delete this problems FIX ME?
this text ""

**Comment by takahirom** [comment]
Please delete it🚮

**Comment by felix925** [comment]
Thank you for answer my question.
I fixed it. Please review exchanged code.

**Comment by takahirom** [comment]
Thanks! LGTM!👍

**Comment by felix925** [comment]
Thank you for your review!!

**Pull request merged**
