### PR TITLE
[iOS]  fix: Show livebadge only on live

### PR DESCRIPTION
**Pull request by KaoruMuta**
## Issue
- N/A

## Overview (Required)
- Show Livebadge only on live.
live_tag

I just judge whether the talk session is on live or not by the value of `session.isOnGoing`.

## Links
-

### CODE REVIEW

**Comment by ry-itto** [comment]
@KaoruMuta This PR can review now?

**Comment by KaoruMuta** [comment]
@ry-itto 
Sorry for late reply.
It seemed that it was conflicted, and I resolved the conflict.

So, this PR can be reviewed now.

**Comment by KaoruMuta** [comment]
I'm relieved, thanks!

**Comment by KaoruMuta** [comment]
Sorry, I find a really minor problem in my scripts.

As usual, the indentation is a tab, but in case it's a space.

Do you think it should be resolved? If you agree, I'm going to resolve.

**Comment by ry-itto** [comment]
I'm sorry... I missed. Please fix it 🙏

**Pull request merged**
