### PR TITLE
#129 add named argument for start time text

### LINKED ISSUE #129: Add named argument for StartTimeText
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add named arguments for StartTimeText
- It is very easy 😄 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/blob/c4541d4948c0f8eef238f1e02ce7842e3ac4a9a8/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt#L75-L77

### PR DESCRIPTION
**Pull request by ShebangDog**
## Issue
- close #129 

## Overview (Required)
- add named arguments for start time text

### CODE REVIEW

**Comment by yurihondo** [comment]
👀

**Comment by yurihondo** [comment]
@ShebangDog 
Thank you for your change.
Could you please merge this branch to the master latest?
(This branch includes the change of `ShebangDog:#143_remove_shopify's_livedata-ktx_dependency`)

**Comment by jmatsu** [comment]
@ShebangDog what's the matter?

**Comment by ShebangDog** [comment]
sorry for causing confusion.
I didn't know how to merge it.
so i want to entrust this issue other person.
I will resolve other issue!!

**Pull request closed without merging**
