### PR TITLE
Make on-demand dynamic feature module

### LINKED ISSUE #147: Use DynamicNavHostFragment and DefaultProgressFragment
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably we can use it.
- Please try it 🚀 

 ## Links	

- https://developer.android.com/guide/navigation/navigation-dynamic

### LINKED ISSUE #334: Test dynamic feature module offline
## Kind (Required)

- Improvement

 ## Overview (Required)

- Testing dynamic feature module is so hard for contributors. Offline testing might reduce the problem. It can do using `FakeSplitInstallManager`.

 ## Links	

- [FakeSplitInstallManager](https://developer.android.com/reference/com/google/android/play/core/splitinstall/testing/FakeSplitInstallManager)
- [My blog](https://medium.com/@star_zero/fakesplitinstallmanager%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9Ftest-dynamic-delivery-offline-f9f672376bab)

### LINKED ISSUE #382: debug.keystore is not sufficient key size
**Overview (Required)**
- I got below error when using bundletool.

```
[BT:0.12.0] Error: Failed to write APK file '/var/folders/wz/p596hjj11cjf55pj9bm6v1pr0000gn/T/7848660085161609879/splits/base-xxhdpi.apk'.
java.io.UncheckedIOException: Failed to write APK file '/var/folders/wz/p596hjj11cjf55pj9bm6v1pr0000gn/T/7848660085161609879/splits/base-xxhdpi.apk'.
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:55)
        at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:42)
        at java.util.function.Function.lambda$andThen$1(Function.java:88)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:570)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:181)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.populateApkSetBuilder(ApkSerializerManager.java:101)
        at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:233)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:117)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:532)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.io.IOException: Failed to generate v1 signature
        at com.android.tools.build.apkzlib.sign.SigningExtension.onOutputZipReadyForUpdate(SigningExtension.java:287)
        at com.android.tools.build.apkzlib.sign.SigningExtension.access$200(SigningExtension.java:57)
        at com.android.tools.build.apkzlib.sign.SigningExtension$1.lambda$beforeUpdate$2(SigningExtension.java:156)
        at com.android.tools.build.apkzlib.zip.ZFile.notify(ZFile.java:2269)
        at com.android.tools.build.apkzlib.zip.ZFile.update(ZFile.java:1002)
        at com.android.tools.build.apkzlib.zip.ZFile.close(ZFile.java:1335)
        at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:196)
        at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:139)
        at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:75)
        at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:53)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:105)
        at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:377)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:185)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.InvalidKeyException: Failed to sign using signer "CERT"
        at com.android.apksig.internal.apk.v1.V1SchemeSigner.signManifest(V1SchemeSigner.java:295)
        at com.android.apksig.internal.apk.v1.V1SchemeSigner.sign(V1SchemeSigner.java:256)
        at com.android.apksig.DefaultApkSignerEngine.outputJarEntries(DefaultApkSignerEngine.java:424)
        at com.android.tools.build.apkzlib.sign.SigningExtension.onOutputZipReadyForUpdate(SigningExtension.java:285)
        ... 18 more
Caused by: java.security.InvalidKeyException: Failed to sign using SHA1withDSA
        at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateSignatureBlock(V1SchemeSigner.java:519)
        at com.android.apksig.internal.apk.v1.V1SchemeSigner.signManifest(V1SchemeSigner.java:293)
        ... 21 more
Caused by: java.security.InvalidKeyException: The security strength of SHA-1 digest algorithm is not sufficient for this key size
        at sun.security.provider.DSA.checkKey(DSA.java:111)
        at sun.security.provider.DSA.engineInitSign(DSA.java:143)
        at java.security.Signature$Delegate.init(Signature.java:1155)
        at java.security.Signature$Delegate.chooseProvider(Signature.java:1115)
        at java.security.Signature$Delegate.engineInitSign(Signature.java:1179)
        at java.security.Signature.initSign(Signature.java:530)
        at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateSignatureBlock(V1SchemeSigner.java:515)
        ... 22 more
```

**Steps To Reproduce**

Run below commands.

```
$ ./gradlew clean :android-base:bundleDebug
$ java -jar bundletool-all.jar build-apks \
             --bundle=android-base/build/outputs/bundle/debug/android-base-debug.aab \
             --output=android-base/build/outputs/bundle/debug/android-base-debug.apks \
             --ks=android-base/debug.keystore \
             --ks-pass=pass:android \
             --ks-key-alias=androiddebugkey \
             --key-pass=pass:android \
             --connected-device
```

**Expected behavior**
No error, and create apks fils.

**Screenshots**

**Env:**

**Additional context**

- Using `~/.android/debug.keystore` which is on my computer doesn't occur the error.

### PR DESCRIPTION
**Pull request by STAR-ZERO**
⚠️  **Need fix #382** ⚠️ 

## Issue
- close #334
- close #147 

## Overview (Required)
- Make on-demand dynamic feature module
- For debugging, use FakeInstallSplitManager

## Links
- 

## How to use FakeInstallSplitManager

```shell
cd <path_to/project_root>

# Build with option
./gradlew clean :android-base:bundleDebug -PuseFakeSplit=true

# create apks file
java -jar bundletool-all.jar build-apks \
             --bundle=android-base/build/outputs/bundle/debug/android-base-debug.aab \
             --output=android-base/build/outputs/bundle/debug/android-base-debug.apks \
             --ks=android-base/debug.keystore \
             --ks-pass=pass:android \
             --ks-key-alias=androiddebugkey \
             --key-pass=pass:android \
             --connected-device

# unzip
unzip android-base/build/outputs/bundle/debug/android-base-debug.apks -d android-base/build/outputs/bundle/debug

# Uninstall the app if needed
adb uninstall io.github.droidkaigi.confsched2020.debug

# Create directory for FakeInstallSplitManager
adb shell mkdir -p /sdcard/Android/data/io.github.droidkaigi.confsched2020.debug/files

# Push apks to device
adb push android-base/build/outputs/bundle/debug/splits/* /sdcard/Android/data/io.github.droidkaigi.confsched2020.debug/files

# Install the app
bundletool install-apks --apks=android-base/build/outputs/bundle/debug/android-base-debug.apks
```

### CODE REVIEW

**Comment by STAR-ZERO** [comment]
On 5.x device crash.

```
01-19 13:09:55.370 4950-4950/io.github.droidkaigi.confsched2020.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.confsched2020.debug, PID: 4950
    android.content.res.Resources$NotFoundException: Resource ID #0x7d0b0000
        at android.content.res.Resources.getValue(Resources.java:1233)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2598)
        at android.content.res.Resources.getXml(Resources.java:1098)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:107)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at io.github.droidkaigi.confsched2020.preference.ui.PreferencesFragment.onCreatePreferences(PreferencesFragment.kt:39)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2715)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:379)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1130)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2166)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1935)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1786)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:412)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by STAR-ZERO** [comment]
The same problem was reproduced in a newly created project.

I filed the issue to the Issue Tracker.
https://issuetracker.google.com/issues/147937971

**Comment by STAR-ZERO** [comment]
https://issuetracker.google.com/issues/147937971#comment2

5.x devices problem is caused by appcompat version.
- 1.1.0-rc01
  - working
- 1.1.0
  - not working

This project specifies version1.1.0-rc01 but 1.1.0 is used by other libraries.

```
$ ./gradlew android-base:dependencies
...
|    +--- androidx.appcompat:appcompat:1.1.0-rc01 -> 1.1.0 (*)
...
```

Anyway, I wait for the Issue Tracker reply.

**Comment by STAR-ZERO** [comment]
Let me close.
This project was changed charset so git always detects `gradlew.bat` as dirty after rebase master. It seems the cause of `.gitattributes`. I couldn't fix it.

I will recreate later.

**Comment by takahirom** [comment]
Please let me know if you have anything.🙆

**Pull request closed without merging**
